controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Name;
use app\models\NameSearch;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

class AdminController extends \yii\web\Controller
{

    public function behaviors()
    {
        return [
            [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return !\Yii::$app->user->isGuest && \Yii::$app->user->identity->role == 'admin';
                        }
                    ]
                ]
            ]
        ];
    }

    public function actionIndex(){
        $searchModel = new NameSearch();
        $dapaProvider = $searchModel->search(\Yii::$app->request->post());
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dapaProvider' => $dapaProvider
        ]);
    }

    public function actionConfirm($id){
        $model = $this->_getModel($id);
        $model->status = Name::STATUS_CONFIRM;
        $model->save(false);
        return $this->redirect(['admin/index']);
    }

    public function actionCancel($id){
        $model = $this->_getModel($id);

        if ($model->load(\Yii::$app->request->post()) && $model->save()){
            return $this->redirect(['admin/index']);
        }
        return $this->render('cancel', ['model' => $model]);
    }

    private function _getModel($id){
        $model = Name::findOne($id);
        if(!$model){
            throw new NotFoundHttpException('Модель не найдена');
        }
        return $model;
    }

}

views/admin/cancel.php
<?php
/* @var $this \yii\web\View */
/* @var $model \app\models\Name */
/* @var $form \yii\widgets\ActiveForm */
?>
<?php $form = \yii\widgets\ActiveForm::begin(['method' => 'post']) ?>
<?php echo $form->field($model, 'name')->textInput(['readonly' => true]) ?>
<?php echo $form->field($model, 'memo')->textarea()->label('Причина') ?>
<div class="btn-group">
    <?php echo \yii\helpers\Html::submitInput('Отправить') ?>
</div>
<?php \yii\widgets\ActiveForm::end() ?>

views/admin/index.php
<?php
/* @var $this \yii\web\View */
/* @var $searchModel \app\models\NameSearch */
/* @var $dapaProvider \yii\data\ActiveDataProvider */

echo \yii\grid\GridView::widget([
    'dataProvider' => $dapaProvider,
    'columns' => [
        'user.username',
        'name',
        'updated_at:datetime',
        [
            'class' => \yii\grid\ActionColumn::class,
            'buttons' => [
                'confirm' => function ($url, $model, $key) {
                    return \yii\helpers\Html::a('Одобрить', ['admin/confirm', 'id' => $model->id]);
                },
                'cancel' => function ($url, $model, $key) {
                    return \yii\helpers\Html::a('Отменить', ['admin/cancel', 'id' => $model->id]);
                }
            ],
            'template' => '{confirm} {cancel}'
        ]
    ],
]);